{% set name = "alchemical-analysis" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tsenapathi/alchemical-analysis/archive/488d7b8a7319f6408c22076cecb201a4dcbebff5.tar.gz
  md5: 7be5d420ce6392bd47505394eccebb7e

build:
  skip: true # [osx]
  entry_points:
    - alchemical_analysis = alchemical_analysis.alchemical_analysis:main
  number: 1

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3
    - setuptools
    - numpy
    - pymbar
    - matplotlib

test:
  imports:
    - alchemical-analysis
  commands:
    - alchemical-analysis -h

about:
  home: https://github.com/MobleyLab/alchemical-analysis.git
  license: MIT
  summary: 'An open tool implementing some recommended practices for analyzing alchemical free energy calculations.'
